First commit of OpenJDK8 JSR292 support
This is still quite a way from being complete, but I'm happy enough
with progress to believe that the implementation is along the right
lines.  At present it can run 11 out of the 17 jtreg invoke tests:

Passed: java/lang/invoke/6987555/Test6987555.java
Passed: java/lang/invoke/6991596/Test6991596.java
Passed: java/lang/invoke/6998541/Test6998541.java
Passed: java/lang/invoke/7157574/Test7157574.java
Passed: java/lang/invoke/AccessControlTest.java
FAILED: java/lang/invoke/CallSiteTest.java
Passed: java/lang/invoke/ClassValueTest.java
FAILED: java/lang/invoke/InvokeDynamicPrintArgs.java
Passed: java/lang/invoke/InvokeGenericTest.java
FAILED: java/lang/invoke/JavaDocExamplesTest.java
Passed: java/lang/invoke/MaxTest.java
FAILED: java/lang/invoke/MethodHandlesTest.java
Passed: java/lang/invoke/MethodTypeTest.java
Passed: java/lang/invoke/PermuteArgsTest.java
Passed: java/lang/invoke/PrivateInvokeTest.java
FAILED: java/lang/invoke/RicochetTest.java
Error:  java/lang/invoke/ThrowExceptionsTest.java
Test results: passed: 11; failed: 5; error: 1

Most of these failures are due to invokedynamic and its associated class
file changes not yet being implemented.  The implementation is currently
sufficient to bootstrap the Java-based JSR292 "engine", and run
invokeExact, etc.

Apart from invokedynamic, the other bit that is missing is an implementation
of an "injector" framework.  OpenJDK8 has removed private VM fields from
various classes, and instead uses injection to add the fields at runtime.

On one hand, this is very useful as it means JamVM no longer has to fit in
with the hotspot specific fields.  But currently it means there's no
VM fields for JamVM to use at all.  For now, I've hacked the classes to
add them, but I need to implement an equivalent field injector before
I can make a release.

Signed-off-by: Robert Lougher <rob@jamvm.org.uk>